### PR TITLE
A1 - Task 1: Contacts, AppIcon, and Accent Color Updated

### PR DESCRIPTION
**Pull request by akanshyabhat**
This PR is related to Assignment 1, Task 1. The contacts have been updated to the information of the PIs. The AppIcon has been changed to an image of a white band-aid against a blue background (part of an image with no copyright) and the accent color has been chosen to match that background.

# *A1 - Task 1: Contacts, AppIcon, and Accent Color Updated*

## :recycle: Current situation & Problem
The Contacts page was using generic information from the template. Similarly, the AppIcon was from the template and there was no specified accent color. 

## :gear: Release Notes 

- Added images for the 3 PIs
- Updated the contacts for the 3 PIs and added it to the ContactList
- Added a new image for the AppIcon
- Updated the AccentColor

## :books: Documentation
No documentation was added as I only made information changes for this specific app. 

## :white_check_mark: Testing
All of the provided tests associated with the pull request have passed. 

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by aydinzahedi — CHANGES_REQUESTED** [review]
Great job with your pull request! Just a few comments:


- I love how you documented everything using the PR template

- Instead of copy-pasting the localized string, you can instead paste the key to the string in the string catalog like this:

`description: String(localized: "YOUR BIO STRING HERE"),`

- The links in the bios don't show up correctly. You can instead create buttons like the phone and email ones on the contact screen. This bit of code could be a helpful example:

`               ContactOption(
                     image: Image(systemName: "safari.fill"), // swiftlint:disable:this accessibility_label_for_image
                     title: "Website",
                     action: {
                         if let url = URL(string: "https://stanford.edu") {
}
}`

**Review by aydinzahedi — CHANGES_REQUESTED** [review]
Thanks for making your revision! Was the safari button working in your emulator? It doesn't work when I run it, and it might be because you're missing the action after the URL: `UIApplication.shared.open(url)`. So sorry that I didn't have that included in the first comment, but you do need the action in order to allow the URL to open. 

```
 ContactOption(
                     image: Image(systemName: "safari.fill"), // swiftlint:disable:this accessibility_label_for_image
                     title: "Website",
                     action: {
                         if let url = URL(string: "YOUR URL HERE") {
                             UIApplication.shared.open(url)
                         }
                     }
```

**Comment by akanshyabhat** [comment]
> Thanks for making your revision! Was the safari button working in your emulator? It doesn't work when I run it, and it might be because you're missing the action after the URL: `UIApplication.shared.open(url)`. So sorry that I didn't have that included in the first comment, but you do need the action in order to allow the URL to open.
> 
> ```
>  ContactOption(
>                      image: Image(systemName: "safari.fill"), // swiftlint:disable:this accessibility_label_for_image
>                      title: "Website",
>                      action: {
>                          if let url = URL(string: "YOUR URL HERE") {
>                              UIApplication.shared.open(url)
>                          }
>                      }
> ```

Hi! I added the action, but for some reason, it's not working. I have pushed the changes so you can take a look. Thank you!

**Review by aydinzahedi — CHANGES_REQUESTED** [review]
Hi Akanshya, were you able to get the website button to work on your end? In the simulator on my computer, the button wouldn't work. If you replace `.init(` with the `ContactOption(` struct instead, you should be good.

**Comment by akanshyabhat** [comment]
Hi Aydin! I checked on the actual simulator and the button should work now!

**Review by aydinzahedi — APPROVED** [review]
Great job, Akanshya!

**Pull request merged**
